# DO NOT EDIT THIS FILE
#
# Please edit /boot/orangepiEnv.txt to set supported parameters
#

setenv load_addr "0x43100000"
setenv overlay_error "false"
# default values
setenv verbosity "1"
setenv console "both"
setenv bootlogo "true"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "on"
setenv bootmenu_first "false"
setenv bootmenu_timeout "20"
setenv bootmenu_default "nvme"
setenv selector_visual_test "none"
setenv selector_visual_hold "8"
setenv selector_logo_preinit "false"
setenv selector_logo_hold "3"

echo "Boot script loaded from ${devtype} ${devnum}"

if test -e ${devtype} ${devnum} ${prefix}orangepiEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}orangepiEnv.txt
	env import -t ${load_addr} ${filesize}
fi

if test -e ${devtype} ${devnum} ${prefix}orangepiBootOnce.txt; then
	echo "Importing one-shot boot request from ${devtype} ${devnum} ${prefix}orangepiBootOnce.txt"
	load ${devtype} ${devnum} ${load_addr} ${prefix}orangepiBootOnce.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${bootonce_target}" = "sd"; then
	echo "One-shot boot target: SD Ubuntu"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv selector_visual_test none
	setenv boot_kernel uImage-5.15.147-sun60iw2
	setenv boot_initrd uInitrd-5.15.147-sun60iw2
	setenv boot_dtb dtb-5.15.147-sun60iw2/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=dc683cb4-0847-4d2f-83f1-184d35749d4c
	setenv extraargs bootchooser=linux-selector-sd
fi

if test "${bootonce_target}" = "nvme"; then
	echo "One-shot boot target: NVMe Ubuntu"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv selector_visual_test none
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	setenv extraargs bootchooser=linux-selector-nvme
fi

if test "${bootgui_selector}" = "true"; then
	echo "Starting Orange Pi boot GUI selector"
	if opi_bootselect ${bootgui_selector_timeout}; then
		if test "${opi_bootselect_target}" = "sd"; then
			setenv bootonce_target sd
			setenv bootchooser bootgui-selector-sd
		else
			setenv bootonce_target nvme
			setenv bootchooser bootgui-selector-nvme
		fi
	else
		echo "Boot GUI selector failed; defaulting to NVMe"
		setenv bootonce_target nvme
		setenv bootchooser bootgui-selector-fail-nvme
	fi
fi

if test "${bootonce_target}" = "sd"; then
	echo "Selected boot target: SD Ubuntu"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv selector_visual_test none
	setenv boot_kernel uImage-5.15.147-sun60iw2
	setenv boot_initrd uInitrd-5.15.147-sun60iw2
	setenv boot_dtb dtb-5.15.147-sun60iw2/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=dc683cb4-0847-4d2f-83f1-184d35749d4c
	setenv extraargs bootchooser=${bootchooser}
fi

if test "${bootonce_target}" = "nvme"; then
	echo "Selected boot target: NVMe Ubuntu"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv selector_visual_test none
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	setenv extraargs bootchooser=${bootchooser}
fi

if test "${selected_boot}" != "true" && test "${extlinux_first}" != "true" && test "${grub_first}" != "true" && test "${direct_booti_first}" != "true"; then
	echo "Default boot target: NVMe Ubuntu"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv selector_visual_test none
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	setenv extraargs bootchooser=boot-script-default-nvme
fi

if test -n "${opi_bootselect_diag}"; then
	setenv extraargs "${extraargs} ${opi_bootselect_diag}"
fi

if test -n "${opi_bootselect_logo}"; then
	setenv extraargs "${extraargs} opibootlogo=${opi_bootselect_logo}"
fi

if test "${selector_logo_preinit}" = "true"; then
	echo "Pre-initializing U-Boot video with stock sunxi_show_logo"
	if sunxi_show_logo; then
		setenv selector_logo_diag "uboot-logo-preinit-ok"
	else
		setenv selector_logo_diag "uboot-logo-preinit-fail"
	fi
	setenv extraargs "${extraargs} ${selector_logo_diag}"
	sleep ${selector_logo_hold}
fi

if test "${selector_console}" = "true"; then
	echo "Forcing selector output to serial and video console"
	usb start
	setenv stdout "vidconsole,serial"
	setenv stderr "vidconsole,serial"
	setenv stdin "serial,usbkbd"
	cls
fi

if test "${selector_bitmap}" = "true"; then
	echo "selector_bitmap=true ignored: sunxi_show_bmp is unsafe from boot.scr on this BSP"
fi

if test "${selector_visual_test}" = "colorbar"; then
	echo "Running bounded U-Boot DRM colorbar visual test"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	if sunxi_drm_env; then
		setenv pre_colorbar_diag "${opi_drm_diag}"
	else
		setenv pre_colorbar_diag "drm_diag=missing"
	fi
	sunxi_backlihgt on
	if sunxi_drm colorbar 1; then
		setenv extraargs bootchooser=uboot-visual-colorbar-ok
	else
		setenv extraargs bootchooser=uboot-visual-colorbar-fail
	fi
	if sunxi_drm_env; then
		setenv post_colorbar_diag "${opi_drm_diag}"
	else
		setenv post_colorbar_diag "drm_diag=missing"
	fi
	setenv extraargs "${extraargs} opi_pre_${pre_colorbar_diag} opi_post_${post_colorbar_diag}"
	sleep ${selector_visual_hold}
fi

if test "${selector_visual_test}" = "fbtest"; then
	echo "Running bounded U-Boot DRM framebuffer visual test"
	setenv selected_boot true
	setenv extlinux_first false
	setenv bootmenu_first false
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	if sunxi_drm_env; then
		setenv pre_fbtest_diag "${opi_drm_diag}"
	else
		setenv pre_fbtest_diag "drm_diag=missing"
	fi
	sunxi_backlihgt on
	if sunxi_drm fbtest; then
		setenv extraargs bootchooser=uboot-visual-fbtest-ok
	else
		setenv extraargs bootchooser=uboot-visual-fbtest-fail
	fi
	if test -z "${opi_fbtest_diag}"; then
		setenv opi_fbtest_diag "fbtest=unset"
	fi
	if sunxi_drm_env; then
		setenv post_fbtest_diag "${opi_drm_diag}"
	else
		setenv post_fbtest_diag "drm_diag=missing"
	fi
	setenv extraargs "${extraargs} opi_pre_${pre_fbtest_diag} opi_fb_${opi_fbtest_diag} opi_post_${post_fbtest_diag}"
	sleep ${selector_visual_hold}
fi

if test "${bootmenu_first}" = "true"; then
	echo "Starting U-Boot bootmenu selector"
	echo "Starting USB for bootmenu keyboard input"
	usb start
	setenv stdin "serial,usbkbd"
	setenv stdout "serial,vidconsole"
	setenv stderr "serial,vidconsole"
	setenv bootmenu_delay "${bootmenu_timeout}"
	setenv selected_boot true
	setenv extlinux_first false
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	setenv extraargs bootchooser=uboot-bootmenu-nosel
	setenv bootmenu_boot_nvme "setenv selected_boot true; setenv extlinux_first false; setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck; setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck; setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b; setenv extraargs bootchooser=uboot-bootmenu-nvme"
	setenv bootmenu_boot_sd "setenv selected_boot true; setenv extlinux_first false; setenv boot_kernel uImage-5.15.147-sun60iw2; setenv boot_initrd uInitrd-5.15.147-sun60iw2; setenv boot_dtb dtb-5.15.147-sun60iw2/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=dc683cb4-0847-4d2f-83f1-184d35749d4c; setenv extraargs bootchooser=uboot-bootmenu-sd"
	setenv bootmenu_boot_verbose "setenv selected_boot true; setenv extlinux_first false; setenv verbosity 7; setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck; setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck; setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b; setenv extraargs bootchooser=uboot-bootmenu-nvme-verbose"
	if test "${bootmenu_default}" = "sd"; then
		setenv bootmenu_0 "Ubuntu SD - stock kernel=run bootmenu_boot_sd"
		setenv bootmenu_1 "Ubuntu NVMe - cyberdeck kernel=run bootmenu_boot_nvme"
	else
		setenv bootmenu_0 "Ubuntu NVMe - cyberdeck kernel=run bootmenu_boot_nvme"
		setenv bootmenu_1 "Ubuntu SD - stock kernel=run bootmenu_boot_sd"
	fi
	setenv bootmenu_2 "Ubuntu NVMe - verbose boot=run bootmenu_boot_verbose"
	bootmenu ${bootmenu_timeout}
fi

if test "${grub_first}" = "true"; then
	echo "Trying GRUB EFI from ${devtype} ${devnum} ${prefix}EFI/BOOT/BOOTAA64.EFI"
	if load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}EFI/BOOT/BOOTAA64.EFI; then
		if load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}; then
			fdt addr ${fdt_addr_r}
			fdt resize 65536
			bootefi ${kernel_addr_r} ${fdt_addr_r}
		else
			bootefi ${kernel_addr_r} ${fdtcontroladdr}
		fi
	fi
	echo "GRUB EFI path returned or failed; falling back to legacy bootm"
fi

if test "${extlinux_first}" = "true"; then
	echo "Orange Pi 4 Pro extlinux dispatcher starting; default boots configured DEFAULT entry"
	echo "Trying extlinux from ${devtype} ${devnum} ${prefix}extlinux/extlinux.conf"
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}extlinux/extlinux.conf; then
		if test "${selector_prompt}" = "true"; then
			sysboot -p ${devtype} ${devnum}:${distro_bootpart} any ${scriptaddr} ${prefix}extlinux/extlinux.conf
		else
			sysboot ${devtype} ${devnum}:${distro_bootpart} any ${scriptaddr} ${prefix}extlinux/extlinux.conf
		fi
	fi
	echo "extlinux path returned or failed; falling back to legacy bootm"
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlyprintk=sunxi-uart,0x02500000 initcall_debug=0 ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}";
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

part uuid ${devtype} ${devnum}:1 partuuid

if test -z "${rootdev}"; then rootdev=PARTUUID="${partuuid}"; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} clk_ignore_unused swiotlb=65536 usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi
if test "${selected_boot}" != "true"; then setenv bootargs "${bootargs} bootchooser=legacy-bootm-fallback"; fi

if test "${direct_booti_first}" = "true"; then
	echo "Trying direct booti with Image/initrd/DTB from ${devtype} ${devnum} ${prefix}"
	setenv booti_bootargs "${bootargs} bootchooser=direct-booti-nvme"
	if load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}initrd.img-5.15.147-sun60iw2-cyberdeck; then
		setenv ramdisk_size ${filesize}
		if load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image-5.15.147-sun60iw2-cyberdeck; then
			if load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; then
				setenv bootargs "${booti_bootargs}"
				fdt addr ${fdt_addr_r}
				fdt resize 65536
				booti ${kernel_addr_r} ${ramdisk_addr_r}:${ramdisk_size} ${fdt_addr_r}
			fi
		fi
	fi
	echo "direct booti path returned or failed; falling back to legacy bootm"
fi

if test -z "${boot_initrd}"; then setenv boot_initrd "uInitrd"; fi
if test -z "${boot_kernel}"; then setenv boot_kernel "uImage"; fi
if test -z "${boot_dtb}"; then setenv boot_dtb "dtb/${fdtfile}"; fi

load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}${boot_initrd}
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}${boot_kernel}

load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}${boot_dtb}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/allwinner/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done

bootm ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
