# DO NOT EDIT THIS FILE
#
# Please edit /boot/orangepiEnv.txt to set supported parameters
#

setenv load_addr "0x43100000"
setenv overlay_error "false"
# default values
setenv verbosity "1"
setenv console "both"
setenv bootlogo "true"
setenv rootfstype "ext4"
setenv docker_optimizations "on"
setenv earlycon "on"
setenv bootmenu_first "false"
setenv bootmenu_timeout "20"

echo "Boot script loaded from ${devtype} ${devnum}"

if test -e ${devtype} ${devnum} ${prefix}orangepiEnv.txt; then
	load ${devtype} ${devnum} ${load_addr} ${prefix}orangepiEnv.txt
	env import -t ${load_addr} ${filesize}
fi

if test "${selector_console}" = "true"; then
	echo "Forcing selector output to serial and video console"
	setenv stdout "vidconsole,serial"
	setenv stderr "vidconsole,serial"
	setenv stdin "serial"
	cls
fi

if test "${selector_bitmap}" = "true"; then
	echo "selector_bitmap=true ignored: sunxi_show_bmp is unsafe from boot.scr on this BSP"
fi

if test "${bootmenu_first}" = "true"; then
	echo "Starting U-Boot bootmenu selector"
	echo "Starting USB for bootmenu keyboard input"
	usb start
	setenv stdin "serial,usbkbd"
	setenv stdout "serial,vidconsole"
	setenv stderr "serial,vidconsole"
	setenv bootmenu_delay "${bootmenu_timeout}"
	setenv selected_boot true
	setenv extlinux_first false
	setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck
	setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck
	setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb
	setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b
	setenv extraargs bootchooser=uboot-bootmenu-nosel
	setenv bootmenu_boot_nvme "setenv selected_boot true; setenv extlinux_first false; setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck; setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck; setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b; setenv extraargs bootchooser=uboot-bootmenu-nvme"
	setenv bootmenu_boot_sd "setenv selected_boot true; setenv extlinux_first false; setenv boot_kernel uImage-5.15.147-sun60iw2; setenv boot_initrd uInitrd-5.15.147-sun60iw2; setenv boot_dtb dtb-5.15.147-sun60iw2/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=dc683cb4-0847-4d2f-83f1-184d35749d4c; setenv extraargs bootchooser=uboot-bootmenu-sd"
	setenv bootmenu_boot_verbose "setenv selected_boot true; setenv extlinux_first false; setenv verbosity 7; setenv boot_kernel uImage-5.15.147-sun60iw2-cyberdeck; setenv boot_initrd uInitrd-5.15.147-sun60iw2-cyberdeck; setenv boot_dtb dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; setenv rootdev UUID=eb86cfeb-60c7-4513-bc69-f6d28e9d561b; setenv extraargs bootchooser=uboot-bootmenu-nvme-verbose"
	setenv bootmenu_0 "Ubuntu NVMe - cyberdeck kernel=run bootmenu_boot_nvme"
	setenv bootmenu_1 "Ubuntu SD - stock kernel=run bootmenu_boot_sd"
	setenv bootmenu_2 "Ubuntu NVMe - verbose boot=run bootmenu_boot_verbose"
	bootmenu ${bootmenu_timeout}
fi

if test "${grub_first}" = "true"; then
	echo "Trying GRUB EFI from ${devtype} ${devnum} ${prefix}EFI/BOOT/BOOTAA64.EFI"
	if load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}EFI/BOOT/BOOTAA64.EFI; then
		if load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb/${fdtfile}; then
			fdt addr ${fdt_addr_r}
			fdt resize 65536
			bootefi ${kernel_addr_r} ${fdt_addr_r}
		else
			bootefi ${kernel_addr_r} ${fdtcontroladdr}
		fi
	fi
	echo "GRUB EFI path returned or failed; falling back to legacy bootm"
fi

if test "${extlinux_first}" = "true"; then
	echo "Orange Pi 4 Pro extlinux dispatcher starting; default boots configured DEFAULT entry"
	echo "Trying extlinux from ${devtype} ${devnum} ${prefix}extlinux/extlinux.conf"
	if test -e ${devtype} ${devnum}:${distro_bootpart} ${prefix}extlinux/extlinux.conf; then
		if test "${selector_prompt}" = "true"; then
			sysboot -p ${devtype} ${devnum}:${distro_bootpart} any ${scriptaddr} ${prefix}extlinux/extlinux.conf
		else
			sysboot ${devtype} ${devnum}:${distro_bootpart} any ${scriptaddr} ${prefix}extlinux/extlinux.conf
		fi
	fi
	echo "extlinux path returned or failed; falling back to legacy bootm"
fi

if test "${logo}" = "disabled"; then setenv logo "logo.nologo"; fi

if test "${console}" = "display" || test "${console}" = "both"; then setenv consoleargs "console=tty1"; fi
if test "${console}" = "serial" || test "${console}" = "both"; then setenv consoleargs "console=ttyS0,115200 ${consoleargs}"; fi
if test "${earlycon}" = "on"; then setenv consoleargs "earlyprintk=sunxi-uart,0x02500000 initcall_debug=0 ${consoleargs}"; fi
if test "${bootlogo}" = "true"; then
	setenv consoleargs "splash plymouth.ignore-serial-consoles ${consoleargs}";
else
	setenv consoleargs "splash=verbose ${consoleargs}"
fi

part uuid ${devtype} ${devnum}:1 partuuid

if test -z "${rootdev}"; then rootdev=PARTUUID="${partuuid}"; fi

setenv bootargs "root=${rootdev} rootwait rootfstype=${rootfstype} ${consoleargs} consoleblank=0 loglevel=${verbosity} clk_ignore_unused swiotlb=65536 usb-storage.quirks=${usbstoragequirks} ${extraargs} ${extraboardargs}"

if test "${docker_optimizations}" = "on"; then setenv bootargs "${bootargs} cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1"; fi
if test "${selected_boot}" != "true"; then setenv bootargs "${bootargs} bootchooser=legacy-bootm-fallback"; fi

if test "${direct_booti_first}" = "true"; then
	echo "Trying direct booti with Image/initrd/DTB from ${devtype} ${devnum} ${prefix}"
	setenv booti_bootargs "${bootargs} bootchooser=direct-booti-nvme"
	if load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}initrd.img-5.15.147-sun60iw2-cyberdeck; then
		setenv ramdisk_size ${filesize}
		if load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}Image-5.15.147-sun60iw2-cyberdeck; then
			if load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}dtb-5.15.147-sun60iw2-cyberdeck/allwinner/sun60i-a733-orangepi-4-pro.dtb; then
				setenv bootargs "${booti_bootargs}"
				fdt addr ${fdt_addr_r}
				fdt resize 65536
				booti ${kernel_addr_r} ${ramdisk_addr_r}:${ramdisk_size} ${fdt_addr_r}
			fi
		fi
	fi
	echo "direct booti path returned or failed; falling back to legacy bootm"
fi

if test -z "${boot_initrd}"; then setenv boot_initrd "uInitrd"; fi
if test -z "${boot_kernel}"; then setenv boot_kernel "uImage"; fi
if test -z "${boot_dtb}"; then setenv boot_dtb "dtb/${fdtfile}"; fi

load ${devtype} ${devnum} ${ramdisk_addr_r} ${prefix}${boot_initrd}
load ${devtype} ${devnum} ${kernel_addr_r} ${prefix}${boot_kernel}

load ${devtype} ${devnum} ${fdt_addr_r} ${prefix}${boot_dtb}
fdt addr ${fdt_addr_r}
fdt resize 65536
for overlay_file in ${overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}dtb/allwinner/overlay/${overlay_prefix}-${overlay_file}.dtbo; then
		echo "Applying kernel provided DT overlay ${overlay_prefix}-${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done
for overlay_file in ${user_overlays}; do
	if load ${devtype} ${devnum} ${load_addr} ${prefix}overlay-user/${overlay_file}.dtbo; then
		echo "Applying user provided DT overlay ${overlay_file}.dtbo"
		fdt apply ${load_addr} || setenv overlay_error "true"
	fi
done

bootm ${kernel_addr_r} ${ramdisk_addr_r} ${fdt_addr_r}

# Recompile with:
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr
